# #!/bin/bash
frama-c -saida -saida-tricera-path $TRICERA_PATH -print -lib-entry 1_saida.c 2>&1 >/dev/null
cat tmp_inferred_source_merged.c | awk '/\/\/ STARTFILE/,0' > 2_isp.c
if [[ -s 2_isp.c ]]; then
    frama-c -isp -isp-print -lib-entry 2_isp.c | awk '/\/* Generated by Frama-C */,0' > 3_combined.c
else
    frama-c -isp -isp-print -lib-entry 1_saida.c | awk '/\/* Generated by Frama-C */,0' > 3_combined.c
fi
isp_status=$?
grep "^SAFE" tmp_tricera_result.txt
saida_status=$?
# frama-c -wp -lib-entry 3_combined.c | awk '/Proved goals/{status = $4 != $6} END {exit status}'
frama-c -wp -lib-entry 3_combined.c | awk 'BEGIN { status = 255 } /Proved goals/{status = $4 != $6} END {exit status}'
wp_status=$?
if [[ $wp_status == 0 && $saida_status == 0 && $isp_status == 0 ]]; then
    # No errors!
    exit 0
elif [[ $wp_status == 0 && $saida_status != 0 && $isp_status == 0 ]]; then
    # Only saida error
    exit 1
elif [[ $wp_status == 0 && $saida_status == 0 && $isp_status != 0 ]]; then
    # Only isp error
    exit 2
elif [[ $wp_status == 0 && $saida_status != 0 && $isp_status != 0 ]]; then
    # Only saida and isp error
    exit 3
elif [[ $wp_status != 0 && $saida_status == 0 && $isp_status == 0 ]]; then
    # Only verification error
    exit 4
elif [[ $wp_status != 0 && $saida_status != 0 && $isp_status == 0 ]]; then
    # Only verification and saida error
    exit 5
elif [[ $wp_status != 0 && $saida_status == 0 && $isp_status != 0 ]]; then
    # Only verification and isp error
    exit 6
elif [[ $wp_status != 0 && $saida_status != 0 && $isp_status != 0 ]]; then
    # All of the errors
    exit 7
fi
